### ISSUE TITLE
Type mismatch: cannot convert from List<List<String>> to Iterable<Iterable<String>>

### ISSUE THREAD

**Issue by pawarashish564** [chrisgleissner/jutil#6]
I used this snippet for table printing
```
  Iterable<String> headers = Arrays.asList("firstName", "lastName");
        Iterable<Iterable<String>> rows = Arrays.asList(Arrays.asList("Tom", "Selleck"),
                Arrays.asList("John", "Hillerman"), Arrays.asList("Roger E.", null), Arrays.asList("Larry", "Manetti"));

        System.out.println(TablePrinter.builder().horizontalDividers(true).nullValue("n/a")
                .tableFormat(new Utf8TableFormat()).rowNumbers(true).startRow(1).endRow(3).maxCellWidth(5)
                .wraparound(false).build().print(headers, rows));
      ```
But this showing me error as type mismatch. I'm currently on JDK1.8

**Comment by pawarashish564** [comment]
I changed `Iterable<Iterable<String>>` to `Iterable<List<String>> ` to solve this but I got JNI error class not found.

**Comment by chrisgleissner** [comment]
Thanks for your report. I will investigate this further and get back to you
soon.

**Comment by chrisgleissner** [comment]
I wrote a test using the code you pasted in this ticket and it passed, both on JDK 8 and JDK 11. 

However, I cut a new release with upgraded dependencies and you can try again using it:
```
<dependency>
  <groupId>com.github.chrisgleissner</groupId>
  <artifactId>jutil-table</artifactId>
  <version>1.1.11</version>
</dependency>
```

Also, it may help you find the root cause of this issue by running https://github.com/chrisgleissner/jutil/blob/master/table/src/test/java/com/github/chrisgleissner/jutil/table/TablePrinterTest.java on your machine. At the very end of this test, you can see the code samples from the readme. And I think what you copy pasted in this issue was one of these samples.

This test passes as you can see at https://travis-ci.org/github/chrisgleissner/jutil

**Comment by ashishpawar517** [comment]
thanks for your help. I tried meanwhile I had some error about maven https://stackoverflow.com/questions/61989650/why-maven-cannot-add-my-dependency-to-jar?noredirect=1#comment109638273_61989650 

help if possible
